apiVersion: v1
kind: Service
metadata:
  name: nginx
  # https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#additional-customizations-via-kubernetes-annotations
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: things-nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
